apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - flask
            - run
            - --host=0.0.0.0
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_ENV
              value: development
          image: saulmdo/bookworms-api
          name: api
          resources: {}
          volumeMounts:
            - mountPath: /backend
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
