apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
        - args:
            - npm
            - start
          env:
            - name: NODE_ENV
              value: development
          image: saulmdo/bookworms
          name: client
          resources: {}
          volumeMounts:
            - mountPath: /frontend
              name: client-claim0
            - mountPath: /frontend/node_modules
              name: node-modules
      restartPolicy: Always
      volumes:
        - name: client-claim0
          persistentVolumeClaim:
            claimName: client-claim0
        - name: node-modules
          persistentVolumeClaim:
            claimName: node-modules
status: {}
