apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: lb-backend
  name: lb-backend
spec:
  ports:
    - name: "82"
      port: 82
      targetPort: 80
    - name: "83"
      port: 83
      targetPort: 1936
  selector:
    io.kompose.service: lb-backend
status:
  loadBalancer: {}
