apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: lb-frontend
  name: lb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lb-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: lb-frontend
    spec:
      containers:
        - image: dockercloud/haproxy
          name: lb-frontend
          ports:
            - containerPort: 80
            - containerPort: 1936
          resources: {}
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: lb-frontend-claim0
      restartPolicy: Always
      volumes:
        - name: lb-frontend-claim0
          persistentVolumeClaim:
            claimName: lb-frontend-claim0
status: {}
